import type { Metadata } from "next";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Test Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="author" content="Lucas Hagfoss"/>
      </head>
      <body
        className="antialiased"
      >
        {children}
      </body>
    </html>
  );
};